let index=0, answers=[], timer=null;
const keys=Object.keys(TRAITS); const $=id=>document.getElementById(id);
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id).classList.add('active');$('restartTop').classList.toggle('hidden',id==='intro');window.scrollTo({top:0,behavior:'smooth'});}
function counts(){const c=Object.fromEntries(keys.map(k=>[k,0]));answers.forEach((ans,i)=>{if(ans==null)return;Q[i].a[ans][1].forEach((k,j)=>c[k]+=j===0?2:1)});return c}
function scores(){const c=counts();const ceilings=Object.fromEntries(keys.map(k=>[k,0]));Q.forEach(item=>{keys.forEach(k=>{let best=0;item.a.forEach(a=>{const pos=a[1].indexOf(k);if(pos===0)best=Math.max(best,2);if(pos===1)best=Math.max(best,1)});ceilings[k]+=best})});return Object.fromEntries(keys.map(k=>[k,Math.min(100,Math.round((c[k]/Math.max(1,ceilings[k]))*100))]));}
function topTraits(){const s=scores();return [...keys].sort((a,b)=>s[b]-s[a]).map(k=>[k,s[k]])}
function radarSVG(values,mini=false){const n=keys.length,cx=150,cy=150,maxR=mini?92:108;const pts=keys.map((k,i)=>{const a=-Math.PI/2+i*2*Math.PI/n;const r=maxR*(values[k]/100);return [cx+Math.cos(a)*r,cy+Math.sin(a)*r]});const grid=[.33,.66,1].map(scale=>`<circle cx="${cx}" cy="${cy}" r="${maxR*scale}" fill="none" stroke="rgba(255,255,255,.09)"/>`).join('');const axes=keys.map((k,i)=>{const a=-Math.PI/2+i*2*Math.PI/n;const x=cx+Math.cos(a)*maxR,y=cy+Math.sin(a)*maxR;return `<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="rgba(255,255,255,.07)"/>`}).join('');const labels=mini?'':keys.map((k,i)=>{const a=-Math.PI/2+i*2*Math.PI/n;const x=cx+Math.cos(a)*(maxR+20),y=cy+Math.sin(a)*(maxR+20);return `<text x="${x}" y="${y}" fill="#858d9b" font-size="8" text-anchor="middle" dominant-baseline="middle">${TRAITS[k].short}</text>`}).join('');const polygon=pts.map(p=>p.join(',')).join(' ');const dots=pts.map(p=>`<circle class="pulseDot" cx="${p[0]}" cy="${p[1]}" r="2.6" fill="#d9ff70"/>`).join('');return `<svg viewBox="0 0 300 300" role="img" aria-label="Operating signature radar map">${grid}${axes}<polygon points="${polygon}" fill="rgba(170,184,255,.15)" stroke="#d9ff70" stroke-width="1.4"/>${dots}${labels}</svg>`}
function provisional(){const c=counts();const max=Math.max(1,...Object.values(c));return Object.fromEntries(keys.map(k=>[k,Math.max(8,Math.round(c[k]/max*92))]));}
function updateRail(){const vals=provisional();$('miniRadar').innerHTML=radarSVG(vals,true);const ranked=Object.entries(counts()).sort((a,b)=>b[1]-a[1]);if(ranked[0][1]===0){$('liveLead').textContent='Your pattern is waking up';$('signalText').innerHTML='The map will begin to take shape as your choices repeat.'}else{$('liveLead').textContent=`${TRAITS[ranked[0][0]].short} is emerging`;$('signalText').innerHTML=`A pattern is beginning to repeat around <b>${TRAITS[ranked[0][0]].name}</b>. Keep answering instinctively; early signals can still shift.`}$('answeredCount').textContent=`${answers.filter(a=>a!=null).length} answered`}
function renderQuestion(direction=1){clearTimeout(timer);const item=Q[index];$('qCard').classList.remove('questionEnter');void $('qCard').offsetWidth;$('qCard').classList.add('questionEnter');$('phase').textContent=item.phase;$('question').textContent=item.q;$('progressLabel').textContent=`${String(index+1).padStart(2,'0')} / ${Q.length}`;$('progressBar').style.width=`${(index/Q.length)*100}%`;$('back').style.opacity=index===0?'.55':'1';$('saveNote').classList.remove('show');$('options').innerHTML=item.a.map((a,i)=>`<button class="option ${answers[index]===i?'selected':''}" data-i="${i}"><span class="optionKey">${String.fromCharCode(65+i)}</span><span class="optionText">${a[0]}</span></button>`).join('');[...document.querySelectorAll('.option')].forEach(btn=>btn.addEventListener('click',()=>select(Number(btn.dataset.i))));updateRail()}
function select(i){answers[index]=i;document.querySelectorAll('.option').forEach((b,j)=>b.classList.toggle('selected',j===i));$('saveNote').classList.add('show');updateRail();timer=setTimeout(()=>{if(index<Q.length-1){index++;renderQuestion(1)}else{finish()}},420)}
function goBack(){clearTimeout(timer);if(index===0){show('intro');return}index--;renderQuestion(-1)}
function finish(){show('mapping');const statuses=['Reading repeated signals...','Comparing dominant modes...','Finding your primary pattern...','Rendering the map...'];let s=0;$('mapStatus').textContent=statuses[0];const int=setInterval(()=>{s++;if(s<statuses.length)$('mapStatus').textContent=statuses[s];else{clearInterval(int);renderResults();show('results')}},520)}
function patternFor(top){const a=top[0][0],b=top[1][0];const pair=PAIRS[`${a}|${b}`]||PAIRS[`${b}|${a}`];if(pair)return pair;return [`${TRAITS[a].short} ${TRAITS[b].short}`,`Your strongest pattern combines ${TRAITS[a].name.toLowerCase()} with ${TRAITS[b].name.toLowerCase()}: two modes that reinforce how you naturally create value.`]}
function renderResults(){const s=scores(),top=topTraits(),pat=patternFor(top);$('resultPattern').textContent=pat[0];$('resultTag').textContent=pat[1];$('bigRadar').innerHTML=radarSVG(s,false);$('resultOrb').innerHTML=radarSVG(s,true);$('signals').innerHTML=top.slice(0,3).map(([k,v])=>`<div class="sig"><div class="sigTop"><div class="sigName">${TRAITS[k].name}</div><div class="sigScore">${v}</div></div><p>${TRAITS[k].desc}</p></div>`).join('');$('equation').innerHTML=`<b>Your pattern:</b><br><span>${TRAITS[top[0][0]].name}</span> + <span>${TRAITS[top[1][0]].name}</span> + ${TRAITS[top[2][0]].name}`;$('scoreList').innerHTML=top.map(([k,v])=>`<div class="scoreRow"><span>${TRAITS[k].name}</span><div class="scoreTrack"><div class="scoreFill" style="width:${v}%"></div></div><span class="scoreNum">${v}</span></div>`).join('');$('moves').innerHTML=top.slice(0,3).map(([k],i)=>`<div class="proseBlock"><b>0${i+1} · ${TRAITS[k].name}</b><p>${TRAITS[k].move}</p></div>`).join('');$('edges').innerHTML=top.slice(0,3).map(([k],i)=>`<div class="proseBlock"><b>0${i+1} · ${TRAITS[k].name}</b><p>${TRAITS[k].edge}</p></div>`).join('');$('sharePattern').textContent=pat[0];$('chips').innerHTML=top.slice(0,3).map(([k,v])=>`<span class="chip">${TRAITS[k].short}<b>${v}</b></span>`).join('');$('quote').textContent=pat[1];window.__result={s,top,pat};try{localStorage.setItem('operatingSignature:lastResult',JSON.stringify({answers,s,top,pat,savedAt:new Date().toISOString()}));$('savedResultBtn').classList.remove('hidden')}catch(e){}}
function reset(){index=0;answers=[];clearTimeout(timer);show('intro');updateRail()}
function copyResult(){const r=window.__result;if(!r)return;const t=`My Operating Signature: ${r.pat[0]}\n${r.top.slice(0,3).map(([k,v])=>`${TRAITS[k].name}: ${v}`).join(' · ')}\n\n${r.pat[1]}`;navigator.clipboard?.writeText(t).then(()=>{const b=$('copy');const old=b.textContent;b.textContent='Copied';setTimeout(()=>b.textContent=old,1200)})}
function saveCard(){const r=window.__result;if(!r)return;const c=$('shareCanvas'),x=c.getContext('2d');x.fillStyle='#0a0e15';x.fillRect(0,0,c.width,c.height);const g=x.createRadialGradient(1000,100,0,1000,100,650);g.addColorStop(0,'rgba(170,184,255,.22)');g.addColorStop(1,'rgba(10,14,21,0)');x.fillStyle=g;x.fillRect(0,0,c.width,c.height);x.fillStyle='#d9ff70';x.font='700 26px system-ui';x.fillText('OPERATING SIGNATURE',80,100);x.fillStyle='#f4f1e9';x.font='800 84px system-ui';wrapText(x,r.pat[0],80,230,980,92);x.fillStyle='#9ba3b1';x.font='28px system-ui';wrapText(x,r.pat[1],80,500,980,43);let y=780;r.top.slice(0,3).forEach(([k,v])=>{x.fillStyle='#f4f1e9';x.font='600 31px system-ui';x.fillText(TRAITS[k].name,80,y);x.fillStyle='#d9ff70';x.font='800 38px system-ui';x.fillText(String(v),960,y);x.fillStyle='#252b35';x.fillRect(80,y+28,900,12);x.fillStyle='#aab8ff';x.fillRect(80,y+28,900*v/100,12);y+=130});x.fillStyle='#747d8d';x.font='21px system-ui';x.fillText('You are not one type. You are a pattern.',80,1390);const a=document.createElement('a');a.download='my-operating-signature.png';a.href=c.toDataURL('image/png');a.click()}
function wrapText(ctx,text,x,y,maxWidth,lineHeight){const words=text.split(' ');let line='';for(const w of words){const test=line+w+' ';if(ctx.measureText(test).width>maxWidth&&line){ctx.fillText(line,x,y);line=w+' ';y+=lineHeight}else line=test}ctx.fillText(line,x,y)}
const MODE_COPY={systems:'Sees the architecture beneath complexity.',builder:'Turns ideas into working reality.',analyst:'Tests claims against evidence.',strategist:'Finds leverage, sequence, and consequence.',synthesizer:'Combines fragments into new understanding.',innovator:'Creates possibilities beyond the default.',operator:'Creates rhythm, ownership, and execution.',translator:'Makes complexity understandable across contexts.',connector:'Builds the relationships that unlock movement.',explorer:'Learns by moving toward the unfamiliar.'};
$('modeGrid').innerHTML=keys.map(k=>`<div class="modeItem"><b>${TRAITS[k].name}</b><span>${MODE_COPY[k]}</span></div>`).join('');
function openModes(){ $('modeModal').classList.remove('hidden') } function closeModes(){ $('modeModal').classList.add('hidden') }
function loadSaved(){try{const d=JSON.parse(localStorage.getItem('operatingSignature:lastResult'));if(!d||!Array.isArray(d.answers)||d.answers.length!==Q.length)return;answers=d.answers;index=Math.max(0,Q.length-1);renderResults();show('results')}catch(e){}}
function syncSavedButton(){try{const d=JSON.parse(localStorage.getItem('operatingSignature:lastResult'));$('savedResultBtn').classList.toggle('hidden',!(d&&Array.isArray(d.answers)&&d.answers.length===Q.length))}catch(e){$('savedResultBtn').classList.add('hidden')}}
const ATM_KEY='operatingSignature:atmosphere';
function atmosphereState(){try{return JSON.parse(localStorage.getItem(ATM_KEY))||{}}catch(e){return {}}}
function applyAtmosphere(next={},persist=true){const cur={mood:'void',temp:0,bright:100,opacity:78,...atmosphereState(),...next};document.body.dataset.mood=cur.mood;document.querySelectorAll('.mood').forEach(b=>b.classList.toggle('active',b.dataset.mood===cur.mood));$('moodName').textContent=cur.mood[0].toUpperCase()+cur.mood.slice(1);$('temp').value=cur.temp;$('bright').value=cur.bright;$('opacity').value=cur.opacity;const av=Math.abs(cur.temp);$('tempLabel').textContent=av<12?'Neutral':cur.temp<0?`Cool ${av}`:`Warm ${av}`;$('brightLabel').textContent=`${cur.bright}%`;$('opacityLabel').textContent=`${cur.opacity}%`;document.documentElement.style.setProperty('--temp-cool',cur.temp<0?(av/100*.18).toFixed(3):0);document.documentElement.style.setProperty('--temp-warm',cur.temp>0?(av/100*.18).toFixed(3):0);const delta=cur.bright-100;document.documentElement.style.setProperty('--dim',delta<0?Math.min(.34,Math.abs(delta)/100*.55).toFixed(3):0);document.documentElement.style.setProperty('--lift',delta>0?Math.min(.14,delta/100*.36).toFixed(3):0);const a=cur.opacity/100;document.documentElement.style.setProperty('--panel',`rgba(17,22,32,${a})`);if(persist)try{localStorage.setItem(ATM_KEY,JSON.stringify(cur))}catch(e){}}
$('start').onclick=()=>{index=0;answers=[];show('quiz');renderQuestion()};$('back').onclick=goBack;$('exit').onclick=()=>show('intro');$('restartTop').onclick=reset;$('retake').onclick=reset;$('copy').onclick=copyResult;$('save').onclick=saveCard;$('about').onclick=openModes;$('modeClose').onclick=closeModes;$('modeModal').addEventListener('click',e=>{if(e.target===$('modeModal'))closeModes()});$('savedResultBtn').onclick=loadSaved;$('atmoBtn').onclick=()=>$('atmoPanel').classList.toggle('hidden');$('atmoClose').onclick=()=>$('atmoPanel').classList.add('hidden');document.querySelectorAll('.mood').forEach(b=>b.onclick=()=>applyAtmosphere({mood:b.dataset.mood}));$('temp').oninput=e=>applyAtmosphere({temp:Number(e.target.value)});$('bright').oninput=e=>applyAtmosphere({bright:Number(e.target.value)});$('opacity').oninput=e=>applyAtmosphere({opacity:Number(e.target.value)});applyAtmosphere({},false);syncSavedButton();
window.addEventListener('mousemove',e=>{$('glow').style.transform=`translate(${e.clientX-210}px,${e.clientY-210}px)`},{passive:true});
window.addEventListener('keydown',e=>{if(e.key==='Escape'){$('modeModal').classList.add('hidden');$('atmoPanel').classList.add('hidden');return}if(!$('quiz').classList.contains('active'))return;if(e.key==='ArrowLeft')goBack();const n=['1','2','3','4','a','b','c','d'].indexOf(e.key.toLowerCase());if(n>=0)select(n%4)});
updateRail();